name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: |
          export CURR_TAG=$(git describe --abbrev=0 --match='v*.*.*' --tags)
          export PREV_TAG=$(git describe --abbrev=0 --exclude="$CURR_TAG" --match='v*.*.*' --tags)
          sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/## $PREV_TAG/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
  terraform-provider-release:
    name: "Terraform Provider Release"
    needs: [release-notes]
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: "${{ secrets.GPG_PRIVATE_KEY }}"
      gpg-private-key-passphrase: "${{ secrets.PASSPHRASE }}"
    with:
      release-notes: true
      setup-go-version-file: ".go-version"
      product-version: "${{ github.ref_name }}"
